{
    'name': 'Hospital',
    'version': '15.0.3.0.0',
    'summary': '',
    'category': 'Customizations',
    'author': 'Anton Zaporozhets',
    'website': '',
    'license': 'OPL-1',
    'depends': [],
    'external_dependencies': {'python': [], },
    'data': [
        'security/ir.model.access.csv',
        'views/hr_hospital_menus.xml',
        'views/patient_view.xml',
        'views/doctor_view.xml',
        'views/doctor_specialization_view.xml',
        'views/diseases_handbook_view.xml',
        'views/medtest_handbook_view.xml',
        'views/contact_person_view.xml',
        'views/personal_doctor_history_view.xml',
        'views/doctors_appointment_view.xml',
        'views/visit_doctor_view.xml',
        'views/diagnosis_history_view.xml',
        'views/medtest_views.xml',
        'wizard/change_personal_doctor_multi_wizard_view.xml',
        'wizard/disease_report_wizard_view.xml',
        'reports/report_disease.xml',
        'reports/report_doctor.xml',
        'reports/report.xml',
    ],
    'demo': [
    ],
    'installable': True,
    'auto_install': False,
    'price': 0,
    'currency': 'UAH',
}
