from . import personal_data_mixin
from . import patient
from . import doctor
from . import doctor_specialization
from . import diseases_handbook
from . import medtest_handbook
from . import contact_person
from . import doctors_appointment
from . import personal_doctor_history
from . import visit_doctor
from . import diagnosis_history
from . import medtest
